image: ubuntu:latest

before_script:
   - apt-get update
   - apt-get install -qq git build-essential cmake qtbase5-dev qtdeclarative5-dev doxygen cppcheck

my_project:
  script:
    - mkdir build && cd build
    - cmake ..
    - make