image: mizux/android:latest

stages:
  - build
  - test

build:linux:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make

# Won't work since qt5 package don't contains android stuff
build:android:
  stage: build
  script:
    - mkdir build-android && cd build-android
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/android.cmake ..
    - make
